export const ADD_START_INDEX = 'ADD_START_INDEX';
export const ADD_LAST_SCREEN_INDEX = 'ADD_LAST_SCREEN_INDEX';
export const ADD_SCREEN_INDEX_TO_SCREEN_STACK =
  'ADD_SCREEN_INDEX_TO_SCREEN_STACK';
export const ADD_NOTIFICATION_TITLE_ARR = 'ADD_NOTIFICATION_TITLE_ARR';
export const ADD_NOTIFICATION_EVENTS_ARR = 'ADD_NOTIFICATION_EVENTS_ARR';
export const ADD_NOTIFICATION_TOAST_ARR = 'ADD_NOTIFICATION_TOAST_ARR';
export const ADD_NOTIFICATION_OFFERS_ARR = 'ADD_NOTIFICATION_OFFERS_ARR';
export const ADD_NOTIFICATION_OFFERS_HEADER_ARR = 'ADD_NOTIFICATION_OFFERS_HEADER_ARR';
