# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "RNFoodOrderingO.xcodeproj")
    build_app(workspace: "RNFoodOrderingO.xcworkspace", scheme: "RNFoodOrderingO")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end

lane :alpha do
  #sync_code_signing(type: "appstore")    # see code signing guide for more information
  increment_build_number(xcodeproj: "RNFoodOrderingO.xcodeproj")
  cert
  sigh(force: true)
  gym(scheme: "RNFoodOrderingO")
  testflight
  # slack(message: "Successfully distributed a new beta build")
end
